### ISSUE TITLE
document Augment 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#105]
For advanced macros, `Augment` allows us to hook deeper into the TeX input. 

``` javascript
TeX: {Augment: {
          Definitions: {
            macros: {bfit: ['SetFont','bold-italic']}
          }
```

**Comment by dpvc** [comment]
Augment actually allows you to specify modifications to the various MathJax jax and extensions in the MathJax configuration block (rather than having to register a startup hook).  It applies to all the jax, not just TeX.  It is designed to allow you to add to or override the object's methods or properties, but it has some limitations.  For example, since the configuration object is created *before* MathJax is available, you can't refer to MathJax components within the augmentation (e.g., we could not use `MathJax.ElementJax.mml.VARIANT.BOLDITALIC` in the example above).  Also, if you need access to the original method that you are overriding, you need to use a startup hook so that you can save the old value before applying the new one.

**Comment by dpvc** [comment]
Here is an example of adding a javascript-based macro where you supply the macro code (not just a reference to existing code):

``` javascript
MathJax = {
  TeX: {Augment: {
    Definitions: {macros: {bfrac: "myBevelFraction"}},
    Parse: {prototype: {
      myBevelFraction: function (name) {
        var num = this.ParseArg(name),
            den = this.ParseArg(name);
        this.Push(MathJax.ElementJax.mml.mfrac(num,den).With({bevelled: true}));
      }
    }}
  }}
};
```

Here we add a `\bfrac` macro that creates a bevelled fraction.

**Comment by pkra** [comment]
Thanks!

**Comment by pkra** [comment]
I'm punting on this.

**Comment by pkra** [comment]
This can probably be closed.
