### ISSUE TITLE
Some pattern doesn't work in markdown

### ISSUE THREAD

**Issue by qilinxiaoxiang** [mathjax/MathJax-docs#212]
in markdown document

```
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

this works

```
\\(\\int _{\\frac{\\pi }{2}}^{\\pi }xdf(x)=\\)
```

but the right exactly the same with the left, like `a = a`, but this doesn't work, why

```
\\(\\int _{\\frac{\\pi }{2}}^{\\pi }xdf(x)= \\int _{\\frac{\\pi }{2}}^{\\pi }xdf(x) \\) 
```

**Comment by dpvc** [comment]
Many versions of Markdown use underscores (`_`) to delimit italic characters.  If your math includes two underscores, as your second example does, the Markdown engine will replace them by `<em>` and `</em>` (or something similar), and since MathJax does not allow HTML tags within the mathematics it processes, that means it will not typeset that expression (and it would be missing the underscores even if it did).  The Markdown conversion occurs before the page is sent to the browser, so long before MathJax runs, and so there is nothing MathJax itself can do about that.  You would need to either have a math-aware Markdown engine (several of them have MathJax plugins that handle this situation), or you may be able to escape the underscores by using `\_` rather than `_`.  That is, 

```
\\(\\int\_{\\frac{\\pi }{2}}^{\\pi }xdf(x)= \\int\_{\\frac{\\pi }{2}}^{\\pi }xdf(x)\\) 
```

might work for you.  Alternatively, you may have to mark the mathematics as "verbatim" material (so that Markdown won't be applied to it).  Enclosing the math in backticks (`` ` ``) might do it, though some markdown engines use `<code>` or `<pre>` tags for this, which MathJax ignores by default.  you might need to reconfigure MathJax to process these in that case.  See the [documentation](http://docs.mathjax.org/en/latest/tex.html#tex-support) for more details (search for Markdown).

**Comment by dpvc** [comment]
Also, this is the wrong place to make these sorts of reports.  You should use the [MathJax issue tracker](https://github.com/mathjax/MathJax/issues) for that.  This issue tracker is for bugs in the documentation itself, not for issues with MathJax *per se*.

**Comment by qilinxiaoxiang** [comment]
thank you
