### ISSUE TITLE
Formatting issues within array

### ISSUE THREAD

**Issue by smcjones** [mathjax/MathJax-docs#231]
__The following code does not render correctly:__

```
\begin{array} { | c | c | c | }
{\bf one} & two & {\bf three} \\ \hline
\end{array}
```

__This code does render correctly:__

```
\begin{array} { | c | c | c | }
\bf one & two & \bf three \\ \hline
\end{array}
```

__This code also renders correctly:__

```
{\bf one} two {\bf three}
```

**Comment by dpvc** [comment]
They all work for me.  It may be that your content management system is modifying what you are entering before it puts it into the page.  You might try using your browser's "View Source" function to look at what is actually in the page and make sure that the LaTeX is making to the page intact.

Otherwise you may need to provide a link to a page that exhibits the problem.  Also, you should indicate what browser and operative system you are using.

Finally, this site is the repository for the documentation for MathJax, and issues here should be about problems within the documentation itself, not about MathJax rendering.  For that, you should use the [MathJax issue tracker](https://github.com/mathjax/MathJax/issues) for general render or other problems using MathJax.
